name: Go Test

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  go-test:
    uses: ipdxco/unified-github-workflows/.github/workflows/go-test.yml@skip-32-bit
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
